version: '3.3'

services:
  refferal_system_db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data1/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/1-schema.sql

    env_file:
      - ./.env
   
  refferal_system_web:
    build:
      context: ../app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - staticfiles_refferal_system_value:/app/static/
      - media_refferal_system_value:/app/media/
    depends_on:
      - refferal_system_db
    env_file:
      - .env

  refferal_system_nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles_refferal_system_value:/var/html/static/
    #   - media_refferal_system_value:/var/html/media/

    depends_on:
      - refferal_system_web
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - refferal_system_db
    environment:
      - PGADMIN_DEFAULT_EMAIL=z@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=z
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555
    volumes:
      - ../data/:/app/data/
    ports:
      - "5555:5555"

volumes:
  staticfiles_refferal_system_value:
  media_refferal_system_value: