# Generated by Django 4.2.4 on 2023-08-17 18:37

import datetime

import django.db.models.deletion
import tokens.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(default=tokens.models.get_random_token6, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
        migrations.CreateModel(
            name='TokenActivated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tokens.token', verbose_name='владелец')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_activated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
